platform: linux

image_resource:
  type: docker-image
  source:
    repository: kennethreitz/pipenv

inputs:
- name: src

run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash -ex
    pipenv install --dev
    pipenv run python -m pytest

  dir: src/tests
