platform: linux

image_resource:
  type: docker-image
  source:
    repository: qnib/pytest

inputs:
- name: src

run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash -ex
    pytest

  dir: src/tests
