platform: linux

image_resource:
  type: docker-image
  source:
    repository: adgear-docker.jfrog.io/adgear/pytest
    username: ((artifactory.username))
    password: ((artifactory.password))

inputs:
- name: src

run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash -ex
    pytest

  dir: src/tests
